/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'holidayPackage' : IDL.Null,
  'visaAssistance' : IDL.Null,
  'flightReservation' : IDL.Null,
  'hotelBooking' : IDL.Null,
  'general' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'subject' : Subject,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const InquiryData = IDL.Record({
  'subject' : Subject,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitInquiry' : IDL.Func([InquiryData], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'holidayPackage' : IDL.Null,
    'visaAssistance' : IDL.Null,
    'flightReservation' : IDL.Null,
    'hotelBooking' : IDL.Null,
    'general' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'subject' : Subject,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const InquiryData = IDL.Record({
    'subject' : Subject,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitInquiry' : IDL.Func([InquiryData], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };